import { mkdir, readFile, writeFile } from "node:fs/promises";
import { compileCatalog } from "../src/catalog/compile-catalog.js";
import { parseCsv } from "../src/catalog/csv.js";
import { createProvenanceRegistry } from "../src/catalog/provenance.js";
import { applyCommonnessProjection } from "../src/commonness/catalog-projection.js";
import {
  projectNaerActiveCatalogRows,
  type NaerActiveCatalogRowsFile,
} from "../src/commonness/naer-general-frequency.js";
import { compileGrammarAnnotations } from "../src/grammar/compile-annotations.js";
import { partitionCatalogForProduct } from "../src/product/catalog-partition.js";
import { synchronizeRecordReadings } from "../src/readings/catalog-resolution.js";
import { loadResolvedCatalogSource } from "./load-resolved-catalog-source.js";

const [resolvedSource, grammarSource, provenanceSource, commonnessSource] = await Promise.all([
  loadResolvedCatalogSource(),
  readFile(new URL("../data/source/grammar.sample.csv", import.meta.url), "utf8"),
  readFile(new URL("../data/provenance.csv", import.meta.url), "utf8"),
  readFile(
    new URL(
      "../data/commonness/naer-1141208-active-catalog-rows.json",
      import.meta.url,
    ),
    "utf8",
  ),
]);

const provenance = createProvenanceRegistry(parseCsv(provenanceSource).records);
if (provenance.errors.length > 0) {
  throw new Error(provenance.errors.map((error) => error.message).join("\n"));
}

const result = compileCatalog(resolvedSource.records, provenance.ids);
if (result.errors.length > 0) {
  throw new Error(
    result.errors.map((error) => `row ${error.rowNumber}: ${error.message}`).join("\n"),
  );
}

const grammarRecords = synchronizeRecordReadings(
  parseCsv(grammarSource).records,
  resolvedSource.report,
);
const grammar = compileGrammarAnnotations(
  grammarRecords,
  result.entries,
  provenance.ids,
);
if (grammar.errors.length > 0) {
  throw new Error(
    grammar.errors.map((error) =>
      `${error.rowNumber === 0 ? "catalog" : `row ${error.rowNumber}`}: ${error.message}`
    ).join("\n"),
  );
}

const commonnessRows = JSON.parse(commonnessSource) as NaerActiveCatalogRowsFile;
const commonness = projectNaerActiveCatalogRows(commonnessRows, result.entries);
const appliedCommonness = applyCommonnessProjection(
  result.entries,
  commonness.projection,
);
if (appliedCommonness.unusedProjectionEntryIds.length > 0) {
  throw new Error(
    `commonness projection contains unknown catalog entries: ${appliedCommonness.unusedProjectionEntryIds.join(", ")}`,
  );
}

const partition = partitionCatalogForProduct(appliedCommonness.entries, 5);
const practiceTokens = new Set(
  partition.practice.flatMap((entry) =>
    entry.syllables.flatMap((syllable) => syllable.tokens),
  ),
);
const missingTones = [1, 2, 3, 4, 5]
  .map((tone) => `tone:${tone}`)
  .filter((tokenId) => !practiceTokens.has(tokenId));
if (missingTones.length > 0) {
  throw new Error(`practice catalog is missing tones: ${missingTones.join(", ")}`);
}

const outputUrl = new URL("../src/app/generated/", import.meta.url);
await mkdir(outputUrl, { recursive: true });
const moduleSource = [
  "// Generated by npm run app:catalog. Do not edit manually.",
  'import type { CatalogEntry } from "../../core/model.js";',
  'import type { GrammarAnnotation } from "../../grammar/types.js";',
  "",
  `export const READING_RESOLUTION_DIGEST = ${JSON.stringify(resolvedSource.report.determinismDigest)};`,
  `export const READING_RESOLUTION_COUNTS = ${JSON.stringify(resolvedSource.report.counts)} as const;`,
  `export const READING_RESOLUTION_CHANGED_TEXTS = ${JSON.stringify(resolvedSource.report.changedTexts)} as const;`,
  "",
  `export const COMMONNESS_PROJECTION_DIGEST = ${JSON.stringify(commonness.projection.determinismDigest)};`,
  "",
  `export const PRACTICE_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.practice, null, 2)};`,
  "",
  `export const EVALUATION_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.evaluation, null, 2)};`,
  "",
  `export const GRAMMAR_ANNOTATIONS: Readonly<Record<string, GrammarAnnotation>> = ${JSON.stringify(grammar.annotations, null, 2)};`,
  "",
].join("\n");

await writeFile(new URL("catalog.ts", outputUrl), moduleSource, "utf8");
console.log(
  `wrote ${partition.practice.length} practice and ${partition.evaluation.length} held-out entries with ${Object.keys(grammar.annotations).length} grammar annotations; resolved readings ${JSON.stringify(resolvedSource.report.counts)}; applied commonness to ${appliedCommonness.appliedEntryIds.length} entries; ${commonness.exclusions.length} identity exclusions; ${commonness.unmatchedCatalogEntryIds.length} catalog fallbacks`,
);
