import { mkdir, readFile, writeFile } from "node:fs/promises";
import { compileCatalog } from "../src/catalog/compile-catalog.js";
import { parseCsv } from "../src/catalog/csv.js";
import { createProvenanceRegistry } from "../src/catalog/provenance.js";
import { partitionCatalogForProduct } from "../src/product/catalog-partition.js";

const [source, provenanceSource] = await Promise.all([
  readFile(new URL("../data/source/words.sample.csv", import.meta.url), "utf8"),
  readFile(new URL("../data/provenance.csv", import.meta.url), "utf8"),
]);

const provenance = createProvenanceRegistry(parseCsv(provenanceSource).records);
if (provenance.errors.length > 0) {
  throw new Error(provenance.errors.map((error) => error.message).join("\n"));
}

const result = compileCatalog(parseCsv(source).records, provenance.ids);
if (result.errors.length > 0) {
  throw new Error(
    result.errors.map((error) => `row ${error.rowNumber}: ${error.message}`).join("\n"),
  );
}

const partition = partitionCatalogForProduct(result.entries, 5);
const practiceTokens = new Set(
  partition.practice.flatMap((entry) =>
    entry.syllables.flatMap((syllable) => syllable.tokens),
  ),
);
const missingTones = [1, 2, 3, 4, 5]
  .map((tone) => `tone:${tone}`)
  .filter((tokenId) => !practiceTokens.has(tokenId));
if (missingTones.length > 0) {
  throw new Error(`practice catalog is missing tones: ${missingTones.join(", ")}`);
}

const outputUrl = new URL("../src/app/generated/", import.meta.url);
await mkdir(outputUrl, { recursive: true });
const moduleSource = [
  "// Generated by npm run app:catalog. Do not edit manually.",
  'import type { CatalogEntry } from "../../core/model.js";',
  "",
  `export const PRACTICE_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.practice, null, 2)};`,
  "",
  `export const EVALUATION_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.evaluation, null, 2)};`,
  "",
].join("\n");

await writeFile(new URL("catalog.ts", outputUrl), moduleSource, "utf8");
console.log(
  `wrote ${partition.practice.length} practice and ${partition.evaluation.length} held-out entries`,
);
