import { mkdir, readFile, writeFile } from "node:fs/promises";
import { compileCatalog } from "../src/catalog/compile-catalog.js";
import { parseCsv } from "../src/catalog/csv.js";
import { createProvenanceRegistry } from "../src/catalog/provenance.js";

const [source, provenanceSource] = await Promise.all([
  readFile(new URL("../data/source/words.sample.csv", import.meta.url), "utf8"),
  readFile(new URL("../data/provenance.csv", import.meta.url), "utf8"),
]);

const provenance = createProvenanceRegistry(parseCsv(provenanceSource).records);
if (provenance.errors.length > 0) {
  throw new Error(provenance.errors.map((error) => error.message).join("\n"));
}

const result = compileCatalog(parseCsv(source).records, provenance.ids);
if (result.errors.length > 0) {
  throw new Error(result.errors.map((error) => `row ${error.rowNumber}: ${error.message}`).join("\n"));
}

const selectedEntries = result.entries.slice(0, 10);
const outputUrl = new URL("../src/app/generated/", import.meta.url);
await mkdir(outputUrl, { recursive: true });

const moduleSource = [
  "// Generated by npm run spike:catalog. Do not edit manually.",
  'import type { CatalogEntry } from "../../core/model.js";',
  "",
  `export const SPIKE_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(selectedEntries, null, 2)};`,
  "",
].join("\n");

await writeFile(new URL("catalog.ts", outputUrl), moduleSource, "utf8");
console.log(`wrote ${selectedEntries.length} entries for the interaction spike`);
