import { mkdir, readFile, writeFile } from "node:fs/promises";
import { compileCatalog } from "../src/catalog/compile-catalog.js";
import { parseCsv } from "../src/catalog/csv.js";
import { createProvenanceRegistry } from "../src/catalog/provenance.js";
import { applyCommonnessProjection } from "../src/commonness/catalog-projection.js";
import {
  projectNaerActiveCatalogRows,
  type NaerActiveCatalogRowsFile,
} from "../src/commonness/naer-general-frequency.js";
import {
  DEFAULT_PRODUCT_EVALUATION_CATALOG_SIZE,
  partitionCatalogForProduct,
} from "../src/product/catalog-partition.js";
import {
  applyCatalogSyntaxLegalityArtifact,
  type CatalogSyntaxLegalityArtifact,
} from "../src/syntax/catalog-legality.js";
import {
  applyActiveCatalogSyntaxProfilesArtifact,
  type ActiveCatalogSyntaxProfilesArtifact,
} from "../src/syntax/runtime-profiles.js";
import { loadResolvedCatalogSource } from "./load-resolved-catalog-source.js";

const [
  resolvedSource,
  provenanceSource,
  commonnessSource,
  syntaxLegalitySource,
  syntaxProfilesSource,
] = await Promise.all([
  loadResolvedCatalogSource(),
  readFile(new URL("../data/provenance.csv", import.meta.url), "utf8"),
  readFile(
    new URL(
      "../data/commonness/naer-1141208-active-catalog-rows.json",
      import.meta.url,
    ),
    "utf8",
  ),
  readFile(
    new URL(
      "../data/grammar/formal-syntax-active-catalog-legality.json",
      import.meta.url,
    ),
    "utf8",
  ),
  readFile(
    new URL(
      "../data/grammar/formal-syntax-active-catalog-profiles.json",
      import.meta.url,
    ),
    "utf8",
  ),
]);

const provenance = createProvenanceRegistry(parseCsv(provenanceSource).records);
if (provenance.errors.length > 0) {
  throw new Error(provenance.errors.map((error) => error.message).join("\n"));
}

const result = compileCatalog(resolvedSource.records, provenance.ids);
if (result.errors.length > 0) {
  throw new Error(
    result.errors.map((error) => `row ${error.rowNumber}: ${error.message}`).join("\n"),
  );
}

const commonnessRows = JSON.parse(commonnessSource) as NaerActiveCatalogRowsFile;
const commonness = projectNaerActiveCatalogRows(commonnessRows, result.entries);
const appliedCommonness = applyCommonnessProjection(
  result.entries,
  commonness.projection,
);
if (appliedCommonness.unusedProjectionEntryIds.length > 0) {
  throw new Error(
    `commonness projection contains unknown catalog entries: ${appliedCommonness.unusedProjectionEntryIds.join(", ")}`,
  );
}

const syntaxArtifact = JSON.parse(syntaxLegalitySource) as CatalogSyntaxLegalityArtifact;
const syntaxLegality = applyCatalogSyntaxLegalityArtifact(result.entries, syntaxArtifact);
const syntaxProfilesArtifact = JSON.parse(
  syntaxProfilesSource,
) as ActiveCatalogSyntaxProfilesArtifact;
const syntaxProfiles = applyActiveCatalogSyntaxProfilesArtifact(
  result.entries,
  syntaxLegality.legalEntryIds,
  syntaxProfilesArtifact,
);
const syntaxLegalEntries = appliedCommonness.entries
  .filter((entry) => syntaxLegality.legalEntryIds.has(entry.id));
if (syntaxLegalEntries.length === 0) {
  throw new Error("formal syntax legality gate excluded the complete app catalog");
}
const partition = partitionCatalogForProduct(
  syntaxLegalEntries,
  DEFAULT_PRODUCT_EVALUATION_CATALOG_SIZE,
);
const practiceTokens = new Set(
  partition.practice.flatMap((entry) =>
    entry.syllables.flatMap((syllable) => syllable.tokens),
  ),
);
const missingTones = [1, 2, 3, 4, 5]
  .map((tone) => `tone:${tone}`)
  .filter((tokenId) => !practiceTokens.has(tokenId));
if (missingTones.length > 0) {
  throw new Error(`practice catalog is missing tones: ${missingTones.join(", ")}`);
}

const outputUrl = new URL("../src/app/generated/", import.meta.url);
await mkdir(outputUrl, { recursive: true });
const packagedTexts = new Set(syntaxLegalEntries.map((entry) => entry.prompt.text));
const packagedChangedTexts = resolvedSource.report.changedTexts
  .filter((text) => packagedTexts.has(text));
const moduleSource = [
  "// Generated by npm run app:catalog. Do not edit manually.",
  'import type { CatalogEntry } from "../../core/model.js";',
  'import type { RuntimeSyntaxProfile } from "../../syntax/types.js";',
  "",
  `export const READING_RESOLUTION_DIGEST = ${JSON.stringify(resolvedSource.report.determinismDigest)};`,
  `export const READING_RESOLUTION_COUNTS = ${JSON.stringify(resolvedSource.report.counts)} as const;`,
  `export const READING_RESOLUTION_CHANGED_TEXTS = ${JSON.stringify(packagedChangedTexts)} as const;`,
  "",
  `export const COMMONNESS_PROJECTION_DIGEST = ${JSON.stringify(commonness.projection.determinismDigest)};`,
  `export const SYNTAX_EVIDENCE_DIGEST = ${JSON.stringify(syntaxArtifact.sourceEvidenceDigest)};`,
  `export const SYNTAX_PROFILE_PROJECTION_DIGEST = ${JSON.stringify(syntaxArtifact.sourceProfileProjectionDigest)};`,
  `export const SYNTAX_RULE_INDEX_DIGEST = ${JSON.stringify(syntaxArtifact.sourceRuleIndexDigest)};`,
  `export const SYNTAX_RUNTIME_PROFILES_DIGEST = ${JSON.stringify(syntaxProfilesArtifact.determinismDigest)};`,
  "",
  `export const PRACTICE_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.practice, null, 2)};`,
  "",
  `export const EVALUATION_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(partition.evaluation, null, 2)};`,
  "",
  `export const SYNTAX_PROFILES = JSON.parse(${JSON.stringify(JSON.stringify(syntaxProfiles))}) as readonly RuntimeSyntaxProfile[];`,
  "",
].join("\n");

await writeFile(new URL("catalog.ts", outputUrl), moduleSource, "utf8");
console.log(
  `wrote ${partition.practice.length} practice and ${partition.evaluation.length} held-out syntax-legal entries with ${syntaxProfiles.length} runtime syntax profiles; excluded ${syntaxLegality.exclusions.length} syntax-illegal entries; resolved readings ${JSON.stringify(resolvedSource.report.counts)}; applied commonness to ${appliedCommonness.appliedEntryIds.length} entries; ${commonness.exclusions.length} identity exclusions; ${commonness.unmatchedCatalogEntryIds.length} catalog fallbacks`,
);
