export const FORMAL_GRAMMAR_VERSION = "mandarin-formal-grammar-v1" as const;

export const SYNTAX_CATEGORIES = [
  "Document",
  "Sentence",
  "Clause",
  "ClauseSequence",
  "Coordination",
  "Topic",
  "Subject",
  "Predicate",
  "Object",
  "IndirectObject",
  "Complement",
  "Adjunct",
  "Nominal",
  "NominalHead",
  "NounPhrase",
  "PronounPhrase",
  "ProperNounPhrase",
  "VerbPhrase",
  "AdjectivePhrase",
  "AdverbPhrase",
  "AdpositionPhrase",
  "NumeralPhrase",
  "DeterminerPhrase",
  "ParticlePhrase",
  "ComplementizerPhrase",
  "InterjectionPhrase",
  "SymbolPhrase",
  "UnknownPhrase",
  "RelativeClause",
  "ContentClause",
  "QuotedClause",
  "Punctuation",
  "Lexeme",
] as const;

export const SYNTAX_FEATURE_NAMES = [
  "upos",
  "function",
  "valency",
  "polarity",
  "aspect",
  "modality",
  "voice",
  "questionType",
  "clauseType",
  "complementType",
  "coordinationType",
  "surfacePosition",
  "dependencyRelation",
  "dependencyDirection",
  "recursionDepth",
] as const;

export const FORBIDDEN_SYNTAX_FIELDS = [
  "meaning",
  "definition",
  "sense",
  "semanticRole",
  "animacy",
  "plausibility",
  "embedding",
  "topic",
  "intent",
  "worldKnowledge",
] as const;

export const DEFAULT_DERIVATION_BOUNDS = {
  maximumPhraseDepth: 4,
  maximumClauseNesting: 3,
  maximumClausesPerSentence: 4,
  maximumCoordinationItems: 3,
  maximumConsecutiveModifiers: 3,
  maximumComplementsPerPredicate: 2,
  maximumLexicalEntriesPerUtterance: 12,
} as const;
