import type { InputLayout } from "../core/model.js";
import { toneToken, zhuyinToken } from "./tokens.js";

export const STANDARD_BOPOMOFO_LAYOUT: InputLayout = {
  id: "zhuyin-standard",
  name: "標準注音",
  bindings: {
    Digit1: zhuyinToken("ㄅ"),
    KeyQ: zhuyinToken("ㄆ"),
    KeyA: zhuyinToken("ㄇ"),
    KeyZ: zhuyinToken("ㄈ"),
    Digit2: zhuyinToken("ㄉ"),
    KeyW: zhuyinToken("ㄊ"),
    KeyS: zhuyinToken("ㄋ"),
    KeyX: zhuyinToken("ㄌ"),
    KeyE: zhuyinToken("ㄍ"),
    KeyD: zhuyinToken("ㄎ"),
    KeyC: zhuyinToken("ㄏ"),
    KeyR: zhuyinToken("ㄐ"),
    KeyF: zhuyinToken("ㄑ"),
    KeyV: zhuyinToken("ㄒ"),
    Digit5: zhuyinToken("ㄓ"),
    KeyT: zhuyinToken("ㄔ"),
    KeyG: zhuyinToken("ㄕ"),
    KeyB: zhuyinToken("ㄖ"),
    KeyY: zhuyinToken("ㄗ"),
    KeyH: zhuyinToken("ㄘ"),
    KeyN: zhuyinToken("ㄙ"),
    KeyU: zhuyinToken("ㄧ"),
    KeyJ: zhuyinToken("ㄨ"),
    KeyM: zhuyinToken("ㄩ"),
    Digit8: zhuyinToken("ㄚ"),
    KeyI: zhuyinToken("ㄛ"),
    KeyK: zhuyinToken("ㄜ"),
    Comma: zhuyinToken("ㄝ"),
    Digit9: zhuyinToken("ㄞ"),
    KeyO: zhuyinToken("ㄟ"),
    KeyL: zhuyinToken("ㄠ"),
    Period: zhuyinToken("ㄡ"),
    Digit0: zhuyinToken("ㄢ"),
    KeyP: zhuyinToken("ㄣ"),
    Semicolon: zhuyinToken("ㄤ"),
    Slash: zhuyinToken("ㄥ"),
    Minus: zhuyinToken("ㄦ"),
    Space: toneToken(1),
    Digit6: toneToken(2),
    Digit3: toneToken(3),
    Digit4: toneToken(4),
    Digit7: toneToken(5),
  },
};
